# .github/workflows/deploy.yml

name: Deploy Next.js PWA to GitHub Pages

on:
  push:
    branches:
      - main # این Workflow هر بار که کدی به شاخه main پوش شود، اجرا می‌شود.

permissions:
  contents: write # اجازه نوشتن در ریپازیتوری برای اکشن
  pages: write   # اجازه مدیریت GitHub Pages
  id-token: write # برای امنیت بیشتر (OpenID Connect)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # پوشه‌ای که Next.js خروجی استاتیک را در آن قرار می‌دهد
          # **این خط حیاتی است:** به اکشن می‌گوید که خروجی را به شاخه 'gh-pages' پوش کند.
          # GitHub Pages شما باید از همین شاخه 'gh-pages' سرویس دهد.
          publish_branch: gh-pages
